### ISSUE TITLE
Only "Not closing" will be used to calculate metric totals on the IT Dashboard

### ISSUE THREAD

**Issue by FuhuXia** [ombegov/dcoi#3]
In the guide PDF it states
> Unlike in previous reporting years, only those data centers that are marked as "Not closing" will be included in calculation of optimization metrics progress.

But in runDCOIReport.py, it is evaluated as 
> `row['closingStage'] != 'Closed'`

So for those records valued with 'migration execution', it will be included in the metrics calculation. Any reasoning for this inconsistency?

**Comment by krusynth** [comment]
No, this should be fixed.
