### ISSUE TITLE
Case sensitive or insensitive?

### ISSUE THREAD

**Issue by FuhuXia** [ombegov/dcoi#5]
In validating process, the string values of some column are evaluated case-insensitively, but during reporting process, the sql query is phrased case-sensitive. This will create situation where records passing validation but mis-calculated in report.

For example, a record with closing stage valued as 'closed' will pass validation but create incorrect number in overall and metrics report.

FYI, the following column name and string value pairs are evaluated in the process.

**Closing Stage**:
`Closed`, `Migration Execution`, `Not closing`
**Key Mission Facility**:
`Yes`, `Not`
**Record Validity**:
`Valid Facility`, `Invalid Facility`
**Ownership Type**:
`Using Cloud Provider`, `Agency Owned`, `Colocation`, `Outsourcing`
**Inter-Agency Shared Services Position**:
`None`, `Tenant`, `Provider`
**Electricity is Metered**:
`Yes`, `No`

**Comment by krusynth** [comment]
We should normalize to the official values (title case) when storing the data, but allow case insensitive to be submitted.

**Comment by krusynth** [comment]
@FuhuXia is this `Fixed` with your most recent work as well?

**Comment by FuhuXia** [comment]
Not yet. This will take several more commits along the way when I fix other issues.
